routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layoutHome.default');
});


//form
Route::resource('/form', 'FormController');

Route::resource('/admin', 'AdminController');
Route::resource('/banner', 'BannerController');
Route::resource('/brand', 'BrandController');
Route::resource('/cart', 'CartController');
Route::resource('/contact', 'ContactController');
Route::resource('/label', 'LabelController');
Route::resource('/category', 'CategoryController');
Route::resource('/page', 'PageController');
Route::resource('/tag', 'TagController');
Route::resource('/testimonial', 'TestimonialController');

//Order

Route::resource('/order', 'OrderController');
Route::resource('/orders1', 'Orders1Controller');
Route::resource('/subscriber', 'SubscriberController');
Route::resource('/sponser', 'SponserController');
Route::resource('/product', 'ProductController');
Route::resource('/map_product_tag', 'Map_product_tagController');
Route::resource('/popular_tag', 'Popular_tagController');

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
Use App\Model\Product;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('product/index', compact('products'));

        /*$products= Product::all();
        //dd($products);
        return view('product/index',compact('products'));*/
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            //dd($request->input());
            if($request->hasFile('picture'))
            {
                $data = $request->all();
                $fileName = $request->title.'-'.$request->picture->getClientOriginalName();
                $request->picture->move(public_path('/images/'), $fileName);
                $data['picture']=$fileName;
            }
            else {
                $data['picture'] = null;
            }

            Product::create($data);

            //return redirect()->route('product.index')->withMessage('Product is Inserted Successfully.');
            return redirect()->route('product.index')->with('message','product is added successfully.');
        }

        catch (QueryException $exception) {
            return redirect()->route('product.create')->withInput()->withErrors($exception->getMessage());
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function show(Product $product)
    {
        //$product = Product::findOrall($id);
        return view('product/show',compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
   //public function edit($id)
   public function edit(Product $product)
      {
          //$product = Product::findOrfail($id);
         // dd($product);
       return view('product/edit',compact('product'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
            //dd($request->input());
            if($request->hasFile('picture'))
            {
                $data = $request->all();
                $fileName = $request->title.'-'.$request->picture->getClientOriginalName();
                $request->picture->move(public_path('/images/'), $fileName);
                $data['picture']=$fileName;
            }
            else {
                $data['picture'] = null;
            }

            Product::create($data);

            //return redirect()->route('sponser.index')->withMessage('product is Inserted Successfully.');
            return redirect()->route('product.index')->with('message','product is added successfully.');
        }

        catch (QueryException $exception) {
            return redirect()->route('product.create')->withInput()->withErrors($exception->getMessage());
        }


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function destroy(Product $product)
    {
        try{
            //$product = Product::findOrFail($id)
                $product->Delete();
            return redirect()->route('product.index')->with('message', 'product is deleted Successfully.');

        }catch (QueryException $exception){
            return redirect()->route('product.create')->withErrors($e ->getMessage());
        }
    }

}

resources/views/product/create.blade.php
@extends('layoutHome.default')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">

                <h3 class="card-title text-center"> Create Form </h3>
                <form action="{{url('/product')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label class = "control-label" for="category_id">Category ID</label>
                        <input id="category_id" type="number" name="category_id" value="" placeholder="write Title Name"  class="form-control" >
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="product_title">Product Title</label>
                        <input id="product_title" type="text" name="product_title" value="" placeholder="write product Title Name"  class="form-control" >
                    </div>


                    <div class="form-group">
                        <label class = "control-label" for="picture">Picture</label>
                        <input id="picture" type="file" name="picture" value="" placeholder=""  class="form-control" >
                    </div>


                    <div class="form-group">
                        <label class = "control-label" for="short_description">Short Description</label>
                        <textarea type="text" value="" name="short_description" rows="1" cols="20" placeholder="Your short  description..." id="short_description"  class="form-control" ></textarea>

                    </div>


                    <div class="form-group">
                        <label class = "control-label" for="description">Description</label>

                        <textarea type="text" value="" name="description" rows="1" cols="20" placeholder="Your description..." id="description"  class="form-control"></textarea>

                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="promotional_message">Promotional Message</label>
                        <textarea type="text" value="" name="promotional_message" rows="1" cols="20" placeholder="Your Reason..." id="promotional_message"  class="form-control"></textarea>

                    </div>


                    <div class="form-group">
                        <label class = "control-label" for="additional_information">Additional Information</label>
                        <textarea type="text" value="" name="additional_information" rows="1" cols="20" placeholder="Your Reason..." id="additional_information"  class="form-control"></textarea>
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="price">Price</label>
                        <input id="price" type="number" name="price" value="" placeholder=""  class="form-control" >
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="special_price">Special Price</label>
                        <input id="special_price" type="number" name="special_price" value="" placeholder=""  class="form-control" >
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="offer">Offer</label>
                        <input id="Offer" type="number" name="offer" value="" placeholder=""  class="form-control" >
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="start_date">Start Date</label>
                        <input id="start_date" type="date" name="start_date" value="" placeholder=""  class="form-control" >
                    </div>


                    <div class="form-group">
                        <label class = "control-label" for="end_date">End Date</label>
                        <input id="end_date" type="date" name="end_date" value="" placeholder=""  class="form-control" >
                    </div>


                    <div class="form-group">
                        <label class = "control-label" for="sku">SKU</label>
                        <input id="sku" type="text" name="sku" value="" placeholder=""  class="form-control" >
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="product_url">Product URL</label>
                        <input id="product_url" type="text" name="product_url" value="" placeholder=""  class="form-control" >
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="created_by">Created By</label>
                        <input id="created_by" type="text" name="created_by" value="" placeholder=""  class="form-control" >
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="updated_by">Updated By</label>
                        <input id="updated_by" type="text" name="updated_by" value="" placeholder=""  class="form-control" >
                    </div>


                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Add</button>
                        <button type="submit" class="btn btn-primary">Reset</button>
                    </div>
                </form>
            </div>
        </div>



        @endsection

        @section('product')
            n/a
@endsection

resources/views/product/edit.blade.php
@extends('layoutHome.default')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">

                <h3 class="card-title text-center"> Create Form </h3>

                    <form action="{{url('product/'.$product->id)}}" method="post" enctype="multipart/form-data">

                    @csrf

                    {{ method_field('put') }}

                    <div class="form-group">
                        <label class = "control-label" for="category_id">Category ID</label>
                        <input id="category_id" type="number" name="category_id" value="{{$product->category_id}}" placeholder="write Title Name"  class="form-control" >
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="product_title">Product Title</label>
                        <input id="product_title" type="text" name="product_title" value="{{$product->product_title}}" placeholder="write product Title Name"  class="form-control" required>
                    </div>


                    <div class="form-group">
                        <label class = "control-label" for="picture">Picture</label>
                        <input id="picture" type="file" name="picture" value="{{$product->picture}}" placeholder=""  class="form-control" required>
                        <input type="image" src="{{ asset('images/'.$product->picture) }}" width="100" height="100">
                    </div>


                    <div class="form-group">
                        <label class = "control-label" for="short_description">Short Description</label>
                        <textarea type="text" name="short_description" rows="1" cols="20"  id="short_description"  class="form-control" > {{$product->short_description}}</textarea>


                    </div>


                    <div class="form-group">
                        <label class = "control-label" for="description">Description</label>
                        <textarea type="text" value="{{$product->description}}" name="description" rows="1" cols="20" placeholder="Your description..." id="description"  class="form-control"></textarea>

                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="promotional_message">Promotional Message</label>
                        <textarea type="text" value="{{$product->promotional_message}}" name="promotional_message" rows="1" cols="20" placeholder="Your Reason..." id="promotional_message"  class="form-control"></textarea>

                    </div>


                    <div class="form-group">
                        <label class = "control-label" for="additional_information">Additional Information</label>
                        <textarea type="text" value="{{$product->additional_information}}" name="additional_information" rows="1" cols="20" placeholder="Your Reason..." id="additional_information"  class="form-control"></textarea>
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="price">Price</label>
                        <input id="price" type="number" name="price" value="{{$product->price}}" placeholder=""  class="form-control" >
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="special_price">Special Price</label>
                        <input id="special_price" type="number" name="special_price" value="{{$product->special_price}}}" placeholder=""  class="form-control" >
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="offer">Offer</label>
                        <input id="Offer" type="number" name="offer" value="{{$product->offer}}" placeholder=""  class="form-control" >
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="start_date">Start Date</label>
                        <input id="start_date" type="date" name="start_date" value="{{$product->start_date}}" placeholder=""  class="form-control" >
                    </div>


                    <div class="form-group">
                        <label class = "control-label" for="end_date">End Date</label>
                        <input id="end_date" type="date" name="end_date" value="{{$product->end_date}}" placeholder=""  class="form-control" >
                    </div>


                    <div class="form-group">
                        <label class = "control-label" for="sku">SKU</label>
                        <input id="sku" type="text" name="sku" value="{{$product->sku}}" placeholder=""  class="form-control" >
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="product_url">Product URL</label>
                        <input id="product_url" type="text" name="product_url" value="{{$product->product_url}}" placeholder=""  class="form-control" >
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="created_by">Created By</label>
                        <input id="created_by" type="text" name="created_by" value="{{$product->created_by}}" placeholder=""  class="form-control" >
                    </div>

                    <div class="form-group">
                        <label class = "control-label" for="updated_by">Updated By</label>
                        <input id="updated_by" type="text" name="updated_by" value="{{$product->updated_by}}" placeholder=""  class="form-control" >
                    </div>


                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Add</button>
                        <button type="submit" class="btn btn-primary">Reset</button>
                    </div>
                </form>
            </div>
        </div>



        @endsection
        @section('product')
            n/a
@endsection

resources/views/product/index.blade.php
@extends('layoutHome.default')

@section('content')

    <div class="row">

        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title text-center"> Index Table </h4>
                    <a class="btn btn-success btn-sm easyAccess" href="{{route('product.create')}}"> Again Add<i class="mdi mdi-playlist-plus"></i></a>

                    @if(session('message'))
                        <div class="alert alert-success"> {{session('message')}} </div>
                    @endif

                    @if($errors->any())
                        @foreach($errors->all() as $error)
                            <div class="alert alert-danger"> {{$error}} </div>
                        @endforeach
                    @endif

                    <div class="table-responsive">
                    <a href="product/create" class="btn btn-outline-info">Add New</a>
                        <table class="table table-striped table-bordered table-hover">
                            <thead class="">
                            <tr>
                                <th> ID </th>
                                <th> Category ID </th>
                                <th> Product Title </th>
                                <th> Picture </th>
                                <th> Short_description</th>
                                <th> Description </th>
                                <th> Additional Information </th>
                                <th> Price </th>
                                <th> Special_price </th>
                                <th> Offer </th>
                                <th> Start Date</th>
                                <th> End Date</th>
                                <th> SKU</th>
                                <th> Product URL</th>
                                <th> Created By</th>
                                <th> Updated By</th>
                                <th> Actions </th>
                            </tr>
                            </thead>
                            <tbody>

                            @php
                                $sl = 1;
                            @endphp

                            @foreach($products as $product)
                                <tr>
                                    <td>{{$sl++}}</td>
                                    <td> {{$product->category_id}} </td>
                                    <td> {{$product->product_title}} </td>

                                    <td><img src="{{ asset('images/'.$product->picture) }}" width="100" height="100"></td>

                                    {{-- <td>
                                        @if(!empty($product->picture))
                                            <img src="{{asset("/images/products/".$product->picture)}}" width="150px" height="150px" alt="Not Found"> </td>
                                    @else
                                        <strong> {{"Empty Image"}} </strong>
                                    @endif--}}

                                    <td> {{$product->short_description}}</td>
                                    <td> {{$product->description}}</td>
                                    <td> {{$product->additional_information}}</td>
                                    <td> {{$product->price}}</td>
                                    <td> {{$product->special_price}} </td>
                                    <td> {{$product->offer}} </td>
                                    <td> {{$product->start_date}} </td>
                                    <td> {{$product->end_date}} </td>
                                    <td> {{$product->sku}} </td>
                                    <td> {{$product->product_url}} </td>
                                    <td> {{$product->created_by}} </td>
                                    <td> {{$product->updated_by}} </td>



                                    <td><a href="{{route('product.edit',['id'=>$product->id])}}">Edit |

                                            {!! Form::open(array('url'=>['product',$product->id],'onclick'=>"return confirm ('Are you sure you want to delete this item?');",'method'=>'DELETE')) !!}
                                            <button type="submit" class="btn btn-primary">Delete</button>
                                        {!! Form::close() !!}

                                    </td>

                                   {{-- <td class="actionButton">
                                        <a class="btn btn-success btn-icon" href="{{route('product.show', $product->id)}}"> <i class="mdi mdi-eye"></i> </a>
                                        <a class="btn btn-primary btn-icon" href="{{route('product.edit', $product->id)}}"> <i class="mdi mdi-pencil"></i> </a>
                                        <a class="btn btn-info btn-icon" href="{{route('product.show', $product->id)}}"> <i class="mdi mdi-eye-off"></i> </a>

                                        {!! Form::open(array('url' => route('product.destroy', $product->id),'method' => 'delete', 'class' => 'deleteForm')) !!}
                                        {{ Form::button('<i class="mdi mdi-delete-forever"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-icon'] )  }}
                                        {!! Form::close() !!}
                                    </td>--}}
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>


    </div>

@endsection

@section('product')
    n/a
@endsection

resources/views/product/show.blade.php
@extends('layoutHome.default')

@section('content')

    <div class="card">

        <dl>
            <dt>ID</dt>
            <dd>{{$product->id}}</dd>

            <dt>Category ID</dt>
            <dd>{{$product->category_id}}</dd>

            <dt>Product Title</dt>
            <dd>{{$product->product_title}}</dd>

            <dt>Picture</dt>
            <dd> <img src="{{ asset('images/'.$product->picture) }}" width="100" height="100"></dd>

            <dt>Short Description</dt>
            <dd>{{$product->short_description}}</dd>

            <dt>Description</dt>
            <dd>{{$product->description}}</dd>

            <dt>additional_information</dt>
            <dd>{{$product->additional_information}}</dd>

            <dt>Price</dt>
            <dd>{{$product->price}}</dd>

            <dt>Special Price</dt>
            <dd>{{$product->special_price}}</dd>

            <dt>Offer</dt>
            <dd>{{$product->offer}}</dd>

            <dt>Start Date</dt>
            <dd>{{$product->start_date}}</dd>

            <dt>End Date</dt>
            <dd>{{$product->end_date}}</dd>

            <dt>SKU</dt>
            <dd>{{$product->sku}}</dd>

            <dt>Product Url</dt>
            <dd>{{$product->product_url}}</dd>

            <dt>Created By</dt>
            <dd>{{$product->created_by}}</dd>

            <dt>updated_by</dt>
            <dd>{{$product->updated_by}}</dd>

            <dt>Created At</dt>
            <dd>{{$product->created_at}}</dd>

            <dt>Updated At</dt>
            <dd>{{$product->updated_at}}</dd>
        </dl>

    </div>
@endsection

@section('product')
    n/a
@endsection