routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layoutHome.default');
});


//form
Route::resource('/form', 'FormController');

Route::resource('/admin', 'AdminController');
Route::resource('/banner', 'BannerController');
Route::resource('/brand', 'BrandController');
Route::resource('/cart', 'CartController');
Route::resource('/contact', 'ContactController');
Route::resource('/label', 'LabelController');
Route::resource('/category', 'CategoryController');
Route::resource('/page', 'PageController');
Route::resource('/tag', 'TagController');
Route::resource('/testimonial', 'TestimonialController');

//Order

Route::resource('/order', 'OrderController');
Route::resource('/orders1', 'Orders1Controller');
Route::resource('/subscriber', 'SubscriberController');
Route::resource('/sponser', 'SponserController');
Route::resource('/product', 'ProductController');
Route::resource('/map_product_tag', 'Map_product_tagController');
Route::resource('/popular_tag', 'Popular_tagController');

app/Http/Controllers/LabelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Label;

class LabelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $labels=Label::all();
        //dd($labels);
        return view('label/index', compact('labels'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('label/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            //dd($request->input());
            if($request->hasFile('picture'))
            {
                $data = $request->all();
                $fileName = $request->title.'-'.$request->picture->getClientOriginalName();
                $request->picture->move(public_path('/images/'), $fileName);
                $data['picture']=$fileName;
            }
            else {
                $data['picture'] = null;
            }
            Label::create($data);
            //return redirect()->route('labs.index')->withMessage('Lab is Inserted Successfully.');
            return redirect()->route('label.index')->with('message','picture is Inserted Successfully.');
        } catch(QueryException $exception){
            return redirect()->route('label.create')->withInput()->withErrors($e->getMessage());
        }
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Label $label)
    {
        //$label = Label::findorfail($id);
        return view('label/show',compact('label'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    //public function edit($id)
    public function edit(Label $label)
    {
        // $cart = Cart::findOrfail($id);
        return view('label/edit',compact('label'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Label $label)
    {
        try{
            //$label = Label::findOrFail($id);
            $data = $request->all();
            $label->Update($data);
            return redirect()->route('label.index')->with('message','Label is Updated Successfully.');
        }catch (QueryException $exception){
            return redirect()->route('label.create')->withErrors($exception->getMessage());
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Label $label)
    {
        try{
            //$label = Label::findOrFail($id);
            $label->Delete();
            return redirect()->route('label.index')->with('message','Label is deleted Successfully.');
        }catch (QueryException $exception){
            return redirect()->route('label.create')->withErrors($exception->getMessage());
        }
    }
}

resources/views/label/create.blade.php
@extends('layoutHome.default')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{url('/label')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label class="control-label" for="title">Title</label>
            <input type="text" name="title" placeholder="Title"  class="form-control">
        </div>

        <div class="form-group">
            <label class = "control-label" for="picture">Picture</label>
            <input id="picture" type="file" name="picture" value="" placeholder="Please add your image"  class="form-control" >
        </div>

        <div class="form-group">
            <label>Is Active? </label>
            <input type="radio" name="is_active" value="1">Yes
            <input type="radio" name="is_active" value="0">No
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </form

@endsection

@section('label')
    n/a
@endsection

resources/views/label/edit.blade.php
@extends('layoutHome.default')


@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{url('label/'.$label->id)}}" method="post" enctype="multipart/form-data">
        @csrf

        {{ method_field('put') }}

        <div class="form-group">
            <label class="control-label" for="title">Title</label>
            <input type="text" value="{{$label->title}}" name="title"  class="form-control">
        </div>

        <div class="form-group">
            <label class = "control-label" for="picture">Picture</label>
            <img src="{{ asset('/images/'.$label->picture) }}" width="150"><br><br>
            <input id="picture" type="file" name="picture" value="{{$label->picture}}" placeholder=""  class="" required>
        </div>

        <div class="form-group">
            <label>Is Active? </label>
            @if($label->is_active==1)
                <input type="radio" name="is_active" value="1" checked>Yes
                <input type="radio" name="is_active" value="0">No
            @else
                <input type="radio" name="is_active" value="1">Yes
                <input type="radio" name="is_active" value="0" checked>No
            @endif
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success">Update</button>
        </div>

    </form>


@endsection

resources/views/label/index.blade.php
@extends('layoutHome.default')

@section('content')

    @if (session('message'))
        <div class="alert alert-success">
            {{ session('message') }}
        </div>
    @endif

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <a href="label/create" class="btn btn-outline-info">Add New</a>
    <table class="table table-bordered">

        <thead class="">
        <tr>
            <th>SL</th>
            <th>Title</th>
            <th>Picture</th>
            <th>Action</th>

        </tr>
        </thead>

        @php
            $sl = 0;
        @endphp

        @foreach($labels as $label)
            <tr>
                <td>{{$sl++}}</td>
                <td><a href="{{route('label.show',['id'=>$label->id])}}">{{$label->title}}</a> </td>

                <td><img src="{{asset('images/'.$label->picture)}}" width="100" height="100" alt=""></td>
                <td>

                <td>
                    <a href="{{route('label.edit', $label->id)}}">Edit</a> |
                    {!! Form::open(array('url' => ['label',$label->id],'onclick' =>"return confirm('Are you sure you want to delete this data form the data table'); ",'method'=>'DELETE')) !!}
                    <button type="submit" class="btn btn-primary">Delete</button>
                    {!! Form::close() !!}

                </td>
            </tr>
        @endforeach
    </table>

@endsection

@section('label')
    n/a
@endsection

resources/views/label/show.blade.php
@extends('layoutHome.default')


@section('content')

    <div class="label">

        <dl>
            <dt>ID</dt>
            <dd>{{$label->id}}</dd>

            <dt>Title</dt>
            <dd>{{$label->title}}</dd>

            <dt>picture</dt>
            <dd>{{$label->picture}}</dd>

        </dl>

    </div>
@endsection

@section('label')
    n/a
@endsection