routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layoutHome.default');
});


//form
Route::resource('/form', 'FormController');

Route::resource('/admin', 'AdminController');
Route::resource('/banner', 'BannerController');
Route::resource('/brand', 'BrandController');
Route::resource('/cart', 'CartController');
Route::resource('/contact', 'ContactController');
Route::resource('/label', 'LabelController');
Route::resource('/category', 'CategoryController');
Route::resource('/page', 'PageController');
Route::resource('/tag', 'TagController');
Route::resource('/testimonial', 'TestimonialController');

//Order

Route::resource('/order', 'OrderController');
Route::resource('/orders1', 'Orders1Controller');
Route::resource('/subscriber', 'SubscriberController');
Route::resource('/sponser', 'SponserController');
Route::resource('/product', 'ProductController');
Route::resource('/map_product_tag', 'Map_product_tagController');
Route::resource('/popular_tag', 'Popular_tagController');

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Brand;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $brands = Brand::all();
       // dd($brands);
        return view('brand/index',compact('brands'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('brand/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request);
        //$data = $request->all();
        //dd($data);
       // brand::create($data);/

        try{
            $data = $request->all();
            Brand::create($data);
            return back();
        }catch (QueryException $exception){
            return redirect()->route('brand/create')->withInput()->withErrors($exception->getMessage());
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Brand $brand)
    {
        return view('brand/show',compact('brand'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    //public function edit($id)
    public function edit(Brand $brand)
    {
        // $brand = Brand::findOrfail($id);
        return view('brand/edit',compact('brand'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Brand $brand)
    {
        try{
            //$brand = Brand::findOrFail($id);
            $data = $request->all();
            $brand->Update($data);
            return redirect()->route('brand.index')->with('message','Brand is Updated Successfully.');
        }catch (QueryException $exception){
            return redirect()->route('brand.create')->withErrors($exception->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Brand $brand)
    {
        try{
            //$brand = Brand::findOrFail($id);
            $brand->Delete();
            return redirect()->route('brand.index')->with('message','Brand is deleted Successfully.');
        }catch (QueryException $exception){
            return redirect()->route('brand.create')->withErrors($exception->getMessage());
        }
    }
}

resources/views/brand/create.blade.php
{{--
hi am rana who is that in this moment
 now i am busy . when 9 o clock i will be free after that i wi9ll call you thanks--}}



@extends('layoutHome.default')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{url('/brand')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label class = "control-label" for="title">Title</label>
            <input id="title" type="text" name="title" value="" placeholder="write Title Name"  class="form-control">
        </div>

        <div class="form-group">
            <label class = "control-label" for="is_draft">Is Draft</label>
            <input id="is_draft" type="number" name="is_draft" value="" placeholder=""  class="form-control">
        </div>

        <div class="form-group">
            <label class = "control-label" for="is_active">Is Active</label>
            <input id="is_active" type="number" name="is_active" value="" placeholder=""  class="form-control">
        </div>


        <div class="form-group">
            <label class = "control-label" for="soft_delete">Soft Delete</label>
            <input id="soft_delete" type="number" name="soft_delete" value="" placeholder=""  class="form-control">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>

    </form>

@endsection

@section('brand')
    n/a
@endsection

resources/views/brand/edit.blade.php
@extends('layoutHome.default')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{url('/brand/'.$brand->id)}}" method="post" enctype="multipart/form-data">

        @csrf
        {{ method_field('put') }}

        <div class="form-group">
            <label class = "control-label" for="title">Title</label>
            <input id="title" type="text" name="title" value="{{$brand->title}}" placeholder="write Title Name"  class="form-control" >
        </div>

        <div class="form-group">
            <label class = "control-label" for="is_draft">Is Draft</label>
            <input id="is_draft" type="number" name="is_draft" value="{{$brand->is_draft}}" placeholder=""  class="form-control" >
        </div>

        <div class="form-group">
            <label class = "control-label" for="is_active">Is Active</label>
            <input id="is_active" type="number" name="is_active" value="{{$brand->is_active}}" placeholder=""  class="form-control" >
        </div>

        <div class="form-group">
            <label class = "control-label" for="soft_delete">Soft Delete</label>
            <input id="soft_delete" type="number" name="soft_delete" value="{{$brand->soft_delete}}" placeholder=""  class="form-control" >
        </div>

        <div class="form-group"><button type="submit" class="btn btn-primary">Add</button></div>
        <div class="form-group"><button type="submit" class="btn btn-primary">Reset</button></div>

    </form>

@endsection

@section('brand')
    n/a
@endsection

resources/views/brand/index.blade.php
@extends('layoutHome.default')

@section('content')

    @if (session('message'))
        <div class="alert alert-success">
            {{ session('message') }}
        </div>
    @endif

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <a href="brand/create" class="btn btn-outline-info">Add New</a>
    <table class="table table-bordered">
        <thead class="">
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Is Draft</th>
            <th>Is Active</th>
            <th>Soft Delete</th>
            <th>Action</th>
        </tr>
        </thead>

        @php
            $sl = 0;
        @endphp

    @foreach($brands as $brand)
            <tr>
                <td>{{$sl++}}</td>
                {{--<td><a href="{{url('/form/'.$form->id)}}">{{$form->firstname}}</a> </td>--}}
                <td><a href="{{route('brand.show',['id'=>$brand->id])}}">{{$brand->title}}</a> </td>
                <td>{{$brand->is_draft}}</td>
                <td>{{$brand->is_active}}</td>
                <td>{{$brand->soft_delete}}</td>
                <td>
                    <a href="{{route('brand.edit', $brand->id)}}">Edit</a> |
                    {!! Form::open(array('url' => ['brand',$brand->id],'onclick' =>"return confirm('Are you sure you want to delete this data form the data table'); ",'method'=>'DELETE')) !!}
                    <button type="submit" class="btn btn-primary">Delete</button>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
    </table>

@endsection

@section('brand')
    n/a
@endsection

resources/views/brand/show.blade.php
@extends('layoutHome.default')

@section('content')

    <div class="brand">

        <dl>
            <dt>ID</dt>
            <dd>{{$brand->id}}</dd>

            <dt>Title</dt>
            <dd>{{$brand->title}}</dd>

            <dt>IS Drafte</dt>
            <dd>{{$brand->is_draft}}</dd>

            <dt>IS Active</dt>
            <dd>{{$brand->is_active}}</dd>

            <dt>Soft Delete</dt>
            <dd>{{$brand->soft_delete}}</dd>

            <dt>Created At</dt>
            <dd>{{$brand->created_at}}</dd>

            <dt>Updated At</dt>
            <dd>{{$brand->updated_at}}</dd>
        </dl>

    </div>
@endsection

@section('brand')
    n/a
@endsection