routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layoutHome.default');
});


//form
Route::resource('/form', 'FormController');

Route::resource('/admin', 'AdminController');
Route::resource('/banner', 'BannerController');
Route::resource('/brand', 'BrandController');
Route::resource('/cart', 'CartController');
Route::resource('/contact', 'ContactController');
Route::resource('/label', 'LabelController');
Route::resource('/category', 'CategoryController');
Route::resource('/page', 'PageController');
Route::resource('/tag', 'TagController');
Route::resource('/testimonial', 'TestimonialController');

//Order

Route::resource('/order', 'OrderController');
Route::resource('/orders1', 'Orders1Controller');
Route::resource('/subscriber', 'SubscriberController');
Route::resource('/sponser', 'SponserController');
Route::resource('/product', 'ProductController');
Route::resource('/map_product_tag', 'Map_product_tagController');
Route::resource('/popular_tag', 'Popular_tagController');

app/Http/Controllers/Popular_tagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Popular_tag;

class Popular_tagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $popular_tags = Popular_tag::all();
        //dd($popular_tags);
        return view('popular_tag/index',compact('popular_tags'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('popular_tag/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request);

        //$data = $request->all();
        //dd($data);
        // contact::create($data);

        $popular_tag = new Popular_tag();

        $popular_tag->name = $request['name'];
        $popular_tag->link= $request['link'];
        $popular_tag->soft_delete = $request['soft_delete'];
        $popular_tag->is_draft = $request['is_draft'];

        //dd($popular_tag);
        $popular_tag->save();
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    //public function show($id)
    public function show(Popular_tag $popular_tag)

    {
        //$popular_tag = popular_tag::findorfail($id);
        return view('popular_tag/show',compact('popular_tag'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Popular_tag $popular_tag)
    {
        return view('popular_tag/edit',compact('popular_tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Popular_tag $popular_tag)
    {
        //dd($request);
        try{
            $data = $request->all();
            $popular_tag->update($data);
            return redirect()->route('popular_tag.index')->with('message','Popular Tag is updated succesfully.');
        }catch (QueryException $exception){
            return redirect()->route('popular_tag.create')->withErrors($exception->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Popular_tag $popular_tag)
    {

        // dd($popular_tag);

        try{
            //$popular_tag = Popular_tag::findOrFail($id);
            $popular_tag->Delete();
            return redirect()->route('popular_tag.index')->with('message','Popular Tag is deleted Successfully.');
        }catch (QueryException $exception){
            return redirect()->route('popular_tag.create')->withErrors($exception->getMessage());
        }
    }
}

resources/views/popular_tag/create.blade.php
{{--
Hi I am created.blade.php file--}}



@extends('layoutHome.default')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{url('/popular_tag')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label class = "control-label" for="name">Name</label>
            <input id="name" type="text" name="name" value="" placeholder="write your name"  class="form-control" required>
        </div>

        <div class="form-group">
            <label class = "control-label" for="link">Link</label>
            <input id="link" type="text" name="link" value="" placeholder=""  class="form-control" required>
        </div>


        <div class="form-group">
            <label class = "control-label" for="soft_delete">Soft Delete</label>
            <input id="soft_delete" type="number" name="soft_delete" value="" placeholder=""  class="form-control" >
        </div>

        <div class="form-group">
            <label class = "control-label" for="is_draft">Is Draft</label>
            <input id="is_draft" type="number" name="is_draft" value="" placeholder=""  class="form-control" >
        </div>


        <div class="form-group">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>

    </form>

@endsection

@section('popular_tag')
    n/a
@endsection

resources/views/popular_tag/edit.blade.php
{{--
Hi I am created.blade.php file--}}



@extends('layoutHome.default')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{url('popular_tag/'.$popular_tag->id)}}" method="post" enctype="multipart/form-data">
        @csrf
        {{method_field('put')}}


        <div class="form-group">
            <label class = "control-label" for="name">Name</label>
            <input id="name" type="text" name="name" value="{{$popular_tag->name}}" placeholder="write your name"  class="form-control" required>
        </div>

        <div class="form-group">
            <label class = "control-label" for="link">Link</label>
            <input id="link" type="text" name="link" value="{{$popular_tag->link}}" placeholder=""  class="form-control" required>
        </div>


        <div class="form-group">
            <label class = "control-label" for="soft_delete">Soft Delete</label>
            <input id="soft_delete" type="number" name="soft_delete" value="{{$popular_tag->soft_delete}}" placeholder=""  class="form-control" required>
        </div>

        <div class="form-group">
            <label class = "control-label" for="is_draft">Is Draft</label>
            <input id="is_draft" type="number" name="is_draft" value="{{$popular_tag->is_draft}}" placeholder=""  class="form-control" required>
        </div>


        <div class="form-group">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>

    </form>

@endsection

@section('popular_tag')
    n/a
@endsection

resources/views/popular_tag/index.blade.php
@extends('layoutHome.default')

@section('content')

    @if (session('message'))
        <div class="alert alert-success">
            {{ session('message') }}
        </div>
    @endif

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <a href="popular_tag/create" class="btn btn-outline-info">Add New</a>
    <table class="table table-bordered">

        <thead class="">
        <tr>
            <th>ID</th>
            <th>name</th>
            <th>Link</th>
            <th>Soft Delete</th>
            <th>Is Draft</th>
            <th>Action</th>

        </tr>
        </thead>

        @php
            $sl = 9;
        @endphp

        @foreach($popular_tags as $popular_tag)
            <tr>
                <td>{{++$sl}}</td>

                <td><a href="{{route('popular_tag.show',['id'=>$popular_tag->id])}}">{{$popular_tag->name}}</a> </td>
                <td><a href="{{route('popular_tag.show',['id'=>$popular_tag->id])}}">{{$popular_tag->link}}</a> </td>
                <td>{{$popular_tag->soft_delete}}</td>
                <td>{{$popular_tag->is_draft}}</td>
                <td>
                    <a href="{{route('popular_tag.edit', $popular_tag->id)}}">Edit</a> |
                    {!! Form::open(array('url' => ['popular_tag',$popular_tag->id],'onclick' =>"return confirm('Are you sure you want to delete this data form the data table'); ",'method'=>'DELETE')) !!}
                    <button type="submit" class="btn btn-primary">Delete</button>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
    </table>

@endsection

@section('popular_tag')
    n/a
@endsection

resources/views/popular_tag/show.blade.php
@extends('layoutHome.default')

@section('content')

    <div class="popular_tag">

        <dl>
            <dt>ID</dt>
            <dd>{{$popular_tag->id}}</dd>

            <dt>Name</dt>
            <dd>{{$popular_tag->name}}</dd>

            <dt>Link</dt>
            <dd>{{$popular_tag->link}}</dd>

            <dt>Soft Delete</dt>
            <dd>{{$popular_tag->soft_delete}}</dd>

            <dt>Is Draft</dt>
            <dd>{{$popular_tag->is_draft}}</dd>

        </dl>

    </div>
@endsection

@section('popular_tag')
    n/a
@endsection